version: '3.9'

services:
  db:
    image: postgres:17
    container_name: admin-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password2!
      POSTGRES_DB: admin_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/AdminDashboard.Api
      dockerfile: Dockerfile
    container_name: admin-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgresConnection: Host=db;Port=5432;Database=admin_db;Username=postgres;Password=Password2!
    ports:
      - "5085:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: admin-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata:


